import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const page = await readFile(new URL("./OrganizerReportPage.tsx", import.meta.url), "utf8");
const service = await readFile(new URL("./services/organizerReportService.ts", import.meta.url), "utf8");
const router = await readFile(new URL("../../core/router/AppRouter.tsx", import.meta.url), "utf8");
const edge = await readFile(new URL("../../../supabase/functions/organizer-report/index.ts", import.meta.url), "utf8");
const shared = await readFile(new URL("../../../supabase/functions/_shared/organizerReport.ts", import.meta.url), "utf8");
const migration = await readFile(new URL("../../../supabase/migrations/20260823090000_create_organizer_report_snapshots.sql", import.meta.url), "utf8");

test("route remains exhibition scoped and print uses the selected immutable snapshot", () => {
  assert.match(router, /\/exhibitions\/:id\/organizer-report/);
  assert.match(page, /reports\.find\(\(item\) => item\.id === selectedId\)/);
  assert.match(page, /organizerReportView\(report\)/);
  assert.match(page, /data-report-id=\{report\.report_id\}/);
  assert.match(page, /window\.print\(\)/);
});

test("new snapshots contain current pipeline, open offers and offered company area", () => {
  assert.match(shared, /ORGANIZER_REPORT_SCHEMA_VERSION = 2/);
  assert.match(shared, /openOffersSqm/);
  assert.match(shared, /offeredSqm/);
  assert.match(shared, /selectLatestSnapshot/);
  assert.doesNotMatch(shared, /commercial_area_events/);
  assert.doesNotMatch(shared, /price_stand_area_sqm/);
});

test("report uses the final English-only V1 labels and no unsupported commercial fields", () => {
  for (const label of ["FAIR ORGANIZER REPORT", "REPORT PERIOD", "CURRENT PIPELINE", "COMMERCIAL STATUS", "OPEN OFFERS", "COMPANIES", "OFFERED (m²)", "TOTAL", "This report is automatically generated by VIAWA."]) {
    assert.equal(page.includes(label), true, label);
  }
  for (const forbidden of ["Potential Area", "Potential m²", "Contracted", "CONTRACT (m²)", "organizer-report-note"]) {
    assert.equal(page.includes(forbidden), false, forbidden);
  }
});

test("company rows show offered area only when persisted and total reuses open offers", () => {
  assert.match(page, /company\.offeredSqm === null \? "—" : formatArea\(company\.offeredSqm\)/);
  assert.match(page, /<tfoot>[\s\S]*formatArea\(view\.openOffersSqm\)/);
  assert.match(page, /OPEN OFFERS[\s\S]*formatArea\(view\.openOffersSqm\)/);
});

test("email draft is selected-report bound and success requires a provider message ID", () => {
  assert.match(page, /organizerReportEmailDraft\(report\)/);
  assert.match(page, /Report ID[\s\S]*report\.report_id/);
  assert.match(page, /sendOrganizerReportEmail/);
  assert.match(page, /reportId: report\.report_id/);
  assert.match(service, /organizer-report-email-send/);
  assert.match(service, /!data\?\.sent \|\| !data\.providerMessageId/);
  assert.match(page, /Gmail accepted this report email/);
  assert.doesNotMatch(page, /mailto:|status.{0,10}sent|showToast\([^)]*sent/i);
});

test("temporary Gmail diagnostic is admin-only, authenticated, and exposes safe results only", () => {
  assert.match(page, /profile\?\.is_active && profile\.role === "admin"/);
  assert.match(page, /Check Gmail Connection/);
  assert.match(page, /checkGmailConnection\(\)/);
  assert.match(service, /gmail-refresh-verify/);
  for (const code of ["OAUTH_REFRESH_OK", "OAUTH_INVALID_GRANT", "OAUTH_INVALID_CLIENT", "OAUTH_REFRESH_OTHER"]) {
    assert.equal(page.includes(code) || service.includes(code), true, code);
  }
  assert.doesNotMatch(page + service, /GMAIL_OAUTH_|access_token|refresh_token|client_secret|localStorage|messages\/send/);
  assert.match(service, /body: \{\}/);
  assert.match(page, /Check Gmail Identity/);
  assert.match(service, /gmail-identity-verify/);
  for (const code of ["GMAIL_MAILBOX_LOOKUP_FAILED", "GMAIL_MAILBOX_MISMATCH", "GMAIL_ALIAS_LOOKUP_FAILED", "GMAIL_ALIAS_NOT_FOUND", "GMAIL_ALIAS_NOT_ACCEPTED", "GMAIL_IDENTITY_ALIAS_OK"]) {
    assert.equal(page.includes(code) || service.includes(code), true, code);
  }
  assert.match(page, /Check Gmail UserInfo/);
  assert.match(service, /gmail-userinfo-verify/);
  for (const code of ["USERINFO_HTTP_401", "USERINFO_HTTP_403", "USERINFO_HTTP_OTHER", "USERINFO_MALFORMED_RESPONSE", "USERINFO_EMAIL_MISSING", "USERINFO_EMAIL_OK"]) {
    assert.equal(page.includes(code) || service.includes(code), true, code);
  }
});

test("browser sends only scope and period while server computes authoritative values", () => {
  assert.match(service, /body: \{ exhibitionId, \.\.\.period \}/);
  assert.doesNotMatch(service, /pipelineCounts|openOffersSqm|companies:/);
  assert.match(edge, /buildOrganizerReportSnapshot/);
  assert.match(edge, /application_users/);
});

test("snapshot table remains immutable with active-user SELECT only", () => {
  assert.match(migration, /before update or delete/i);
  assert.match(migration, /revoke all .* authenticated/i);
  assert.doesNotMatch(migration, /for insert\s+to authenticated/i);
  assert.doesNotMatch(migration, /is_active_application_(?:user|admin)/i);
});

test("report markup contains no private CRM data", () => {
  for (const forbidden of ["contact_person", "phone", "opportunity_id", "created_by", "call_notes", "recipientContacts"]) {
    assert.equal(page.includes(forbidden), false);
  }
});
